version: '3.3'
services:
    rstudio:
        image: rocker/tidyverse:4.2.1
        container_name: rstudio
        restart: always
        ports:
            - '80:8787'
        environment:
            - PASSWORD=
            - DISABLE_AUTH=false
            - ROOT=true
            - USERID=1001
            - GROUPID=1001
        volumes:
            - ./workspace:/home/rstudio/workspace
